language: cpp
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-4.8
      - g++-4.8
      - clang-3.6
      - libboost-test-dev
install:
  - if [[ "$CXX" == "g++" ]]; then export CXX="g++-4.8"; fi
  - if [[ "$CXX" == "clang++" ]]; then export CXX="clang++-3.6"; fi
script:
  - make -k all
  - make -k test
