language: cpp
compiler:
#  - gcc
  - clang
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.8-dev
      - libboost-test-dev
script:
  - make -k all
  - make -k test
